import type { AttributeKey, PositionPreset, PresetId } from './types'

type RoleDefinition = [id: string, name: string, description: string, weights: Partial<Record<AttributeKey, number>>]

const makeRoles = (position: PresetId, definitions: RoleDefinition[]): PositionPreset[] => definitions.map(([id, name, description, weights]) => ({ id, name, position, description, weights }))

export const rolePresets: Record<PresetId, PositionPreset[]> = {
  GK: makeRoles('GK', [
    ['GK_TRADITIONAL', 'Traditional Goalkeeper', 'Primarily shot-stopping and positioning; distribution is secondary.', { reactions: 10, acceleration: 1, sprintSpeed: 1, agility: 3, balance: 2, strength: 3, composure: 8, shortPassing: 2, longPassing: 3, ballControl: 1, gkDiving: 10, gkHandling: 10, gkKicking: 6, gkPositioning: 10, gkReflexes: 10 }],
    ['GK_SWEEPER', 'Sweeper Keeper', 'A shot-stopper who also comes off his line and distributes well.', { reactions: 10, acceleration: 4, sprintSpeed: 4, agility: 5, balance: 4, strength: 4, composure: 9, shortPassing: 5, longPassing: 6, ballControl: 4, gkDiving: 9, gkHandling: 9, gkKicking: 9, gkPositioning: 10, gkReflexes: 10 }],
  ]),
  CB: makeRoles('CB', [
    ['CB_STOPPER', 'Stopper', 'Physically confronts attackers and wins tackles and aerial duels.', { ballControl: 3, shortPassing: 5, longPassing: 4, headingAccuracy: 10, acceleration: 6, sprintSpeed: 7, agility: 3, balance: 6, reactions: 9, jumping: 10, stamina: 6, strength: 10, aggression: 10, interceptions: 9, vision: 2, composure: 9, marking: 10, standingTackle: 10, slidingTackle: 9 }],
    ['CB_BALL_PLAYING', 'Ball-Playing Centre Back', 'A strong defender who can confidently progress the ball through passing.', { ballControl: 7, shortPassing: 9, longPassing: 9, headingAccuracy: 8, acceleration: 5, sprintSpeed: 5, agility: 4, balance: 6, reactions: 9, jumping: 8, stamina: 6, strength: 8, aggression: 7, interceptions: 10, vision: 7, composure: 10, marking: 10, standingTackle: 10, slidingTackle: 8 }],
    ['CB_COVER', 'Cover Centre Back', 'A faster defender who protects space behind the defensive line.', { ballControl: 4, shortPassing: 6, longPassing: 6, headingAccuracy: 7, acceleration: 9, sprintSpeed: 10, agility: 7, balance: 7, reactions: 10, jumping: 8, stamina: 7, strength: 9, aggression: 8, interceptions: 10, vision: 3, composure: 9, marking: 10, standingTackle: 10, slidingTackle: 10 }],
  ]),
  FB: makeRoles('FB', [
    ['FB_DEFENSIVE', 'Defensive Fullback', 'Prioritizes defending and protecting the flank.', { ballControl: 5, dribbling: 4, crossing: 5, shortPassing: 6, longPassing: 5, finishing: 1, acceleration: 8, sprintSpeed: 9, agility: 6, balance: 7, reactions: 9, stamina: 9, strength: 8, aggression: 8, interceptions: 10, attackingPosition: 2, vision: 3, composure: 7, marking: 10, standingTackle: 10, slidingTackle: 9 }],
    ['FB_BALANCED', 'Balanced Fullback', 'Contributes both defensively and offensively.', { ballControl: 7, dribbling: 7, crossing: 8, shortPassing: 7, longPassing: 6, finishing: 2, acceleration: 9, sprintSpeed: 9, agility: 8, balance: 8, reactions: 8, stamina: 10, strength: 7, aggression: 7, interceptions: 9, attackingPosition: 5, vision: 6, composure: 8, marking: 9, standingTackle: 9, slidingTackle: 8 }],
    ['FB_ATTACKING', 'Attacking Wingback', 'Constantly overlaps and creates width in attack.', { ballControl: 8, dribbling: 9, crossing: 10, shortPassing: 8, longPassing: 7, finishing: 4, acceleration: 10, sprintSpeed: 10, agility: 9, balance: 8, reactions: 8, stamina: 10, strength: 6, aggression: 6, interceptions: 7, attackingPosition: 8, vision: 7, composure: 7, marking: 7, standingTackle: 7, slidingTackle: 6 }],
    ['FB_INVERTED', 'Inverted Fullback', 'Moves centrally and behaves partly like a midfielder.', { ballControl: 9, dribbling: 8, crossing: 5, shortPassing: 10, longPassing: 9, finishing: 3, acceleration: 8, sprintSpeed: 8, agility: 8, balance: 9, reactions: 9, stamina: 10, strength: 7, aggression: 7, interceptions: 9, attackingPosition: 5, vision: 9, composure: 9, marking: 9, standingTackle: 8, slidingTackle: 7 }],
  ]),
  CDM: makeRoles('CDM', [
    ['CDM_ANCHOR', 'Anchor', 'Sits in front of the defence and protects central areas.', { ballControl: 6, dribbling: 3, shortPassing: 8, longPassing: 8, acceleration: 5, sprintSpeed: 5, agility: 4, balance: 8, reactions: 10, stamina: 9, strength: 10, aggression: 9, interceptions: 10, vision: 6, composure: 9, marking: 10, standingTackle: 10, slidingTackle: 8 }],
    ['CDM_BALL_WINNER', 'Ball-Winning Midfielder', 'Aggressively presses, tackles and recovers possession.', { ballControl: 6, dribbling: 4, shortPassing: 7, longPassing: 6, acceleration: 8, sprintSpeed: 8, agility: 7, balance: 8, reactions: 9, stamina: 10, strength: 9, aggression: 10, interceptions: 10, vision: 4, composure: 8, marking: 9, standingTackle: 10, slidingTackle: 9 }],
    ['CDM_DEEP_PLAYMAKER', 'Deep-Lying Playmaker', 'Starts attacks from deep with passing and vision.', { ballControl: 9, dribbling: 7, shortPassing: 10, longPassing: 10, acceleration: 5, sprintSpeed: 4, agility: 6, balance: 8, reactions: 9, stamina: 8, strength: 7, aggression: 5, interceptions: 8, vision: 10, composure: 10, marking: 8, standingTackle: 7, slidingTackle: 6 }],
    ['CDM_HOLDING', 'Holding Midfielder', 'A balanced defensive midfielder who maintains structure.', { ballControl: 7, dribbling: 5, shortPassing: 9, longPassing: 8, acceleration: 6, sprintSpeed: 6, agility: 5, balance: 8, reactions: 10, stamina: 9, strength: 9, aggression: 8, interceptions: 10, vision: 7, composure: 9, marking: 10, standingTackle: 9, slidingTackle: 8 }],
  ]),
  CM: makeRoles('CM', [
    ['CM_BOX_TO_BOX', 'Box-to-Box', 'Covers huge areas and contributes in both boxes.', { ballControl: 8, dribbling: 7, crossing: 4, shortPassing: 9, longPassing: 8, finishing: 6, curve: 5, acceleration: 7, sprintSpeed: 7, agility: 7, balance: 8, reactions: 9, shotPower: 7, stamina: 10, strength: 7, longShots: 7, aggression: 7, interceptions: 7, attackingPosition: 7, vision: 8, composure: 9, marking: 6, standingTackle: 6, slidingTackle: 5 }],
    ['CM_PLAYMAKER', 'Playmaker', 'Controls possession and creates chances through passing.', { ballControl: 10, dribbling: 9, crossing: 5, shortPassing: 10, longPassing: 10, finishing: 5, curve: 8, acceleration: 6, sprintSpeed: 5, agility: 8, balance: 9, reactions: 9, shotPower: 6, stamina: 8, strength: 5, longShots: 6, aggression: 4, interceptions: 5, attackingPosition: 6, vision: 10, composure: 10, marking: 4, standingTackle: 3, slidingTackle: 2 }],
    ['CM_BALL_WINNER', 'Ball-Winning Midfielder', 'A defensive CM focused on recovering possession.', { ballControl: 6, dribbling: 5, crossing: 2, shortPassing: 8, longPassing: 7, finishing: 2, curve: 2, acceleration: 7, sprintSpeed: 7, agility: 6, balance: 8, reactions: 9, shotPower: 4, stamina: 10, strength: 8, longShots: 3, aggression: 10, interceptions: 10, attackingPosition: 3, vision: 5, composure: 9, marking: 9, standingTackle: 10, slidingTackle: 8 }],
    ['CM_ATTACKING', 'Mezzala / Attacking CM', 'Pushes forward from central midfield to support attacks.', { ballControl: 9, dribbling: 9, crossing: 6, shortPassing: 9, longPassing: 8, finishing: 8, curve: 7, acceleration: 8, sprintSpeed: 7, agility: 9, balance: 8, reactions: 9, shotPower: 8, stamina: 9, strength: 5, longShots: 9, aggression: 4, interceptions: 3, attackingPosition: 10, vision: 9, composure: 9, marking: 3, standingTackle: 2, slidingTackle: 1 }],
  ]),
  CAM: makeRoles('CAM', [
    ['CAM_PLAYMAKER', 'Playmaker', 'The primary creator between midfield and attack.', { ballControl: 10, dribbling: 9, crossing: 5, shortPassing: 10, longPassing: 8, finishing: 6, volleys: 4, curve: 8, acceleration: 7, sprintSpeed: 5, agility: 9, balance: 9, reactions: 9, shotPower: 6, stamina: 7, longShots: 6, attackingPosition: 7, vision: 10, composure: 10 }],
    ['CAM_SHADOW_STRIKER', 'Shadow Striker', 'Makes forward runs and acts almost like a second striker.', { ballControl: 8, dribbling: 8, crossing: 3, shortPassing: 8, longPassing: 5, finishing: 10, volleys: 8, curve: 6, acceleration: 9, sprintSpeed: 8, agility: 8, balance: 8, reactions: 10, shotPower: 9, stamina: 8, longShots: 8, attackingPosition: 10, vision: 7, composure: 10 }],
    ['CAM_DRIBBLING', 'Dribbling Creator', 'Beats players and creates chances by carrying the ball.', { ballControl: 10, dribbling: 10, crossing: 6, shortPassing: 9, longPassing: 6, finishing: 7, volleys: 5, curve: 8, acceleration: 10, sprintSpeed: 8, agility: 10, balance: 10, reactions: 9, shotPower: 6, stamina: 8, longShots: 7, attackingPosition: 8, vision: 9, composure: 9 }],
    ['CAM_LONG_SHOT', 'Long-Shot CAM', 'Operates outside the box and threatens with powerful or finesse shots.', { ballControl: 9, dribbling: 8, crossing: 5, shortPassing: 8, longPassing: 7, finishing: 9, volleys: 7, curve: 10, acceleration: 7, sprintSpeed: 6, agility: 8, balance: 8, reactions: 9, shotPower: 10, stamina: 7, longShots: 10, attackingPosition: 9, vision: 8, composure: 10 }],
  ]),
  WINGER: makeRoles('WINGER', [
    ['WG_EXPLOSIVE', 'Explosive Winger', 'Uses raw speed and acceleration to beat defenders and run behind.', { ballControl: 8, dribbling: 9, crossing: 6, shortPassing: 6, longPassing: 2, finishing: 7, volleys: 4, curve: 6, acceleration: 10, sprintSpeed: 10, agility: 10, balance: 9, reactions: 7, shotPower: 6, stamina: 9, strength: 4, longShots: 6, attackingPosition: 8, vision: 5, composure: 7 }],
    ['WG_TECHNICAL', 'Technical Winger', 'Combines dribbling, passing and control to create chances.', { ballControl: 10, dribbling: 10, crossing: 8, shortPassing: 9, longPassing: 5, finishing: 6, volleys: 4, curve: 8, acceleration: 8, sprintSpeed: 7, agility: 10, balance: 9, reactions: 8, shotPower: 5, stamina: 8, strength: 4, longShots: 6, attackingPosition: 7, vision: 9, composure: 9 }],
    ['WG_INVERTED', 'Inverted Winger', 'Cuts inside onto the preferred foot and attacks goal.', { ballControl: 9, dribbling: 10, crossing: 5, shortPassing: 8, longPassing: 4, finishing: 9, volleys: 7, curve: 10, acceleration: 9, sprintSpeed: 8, agility: 10, balance: 9, reactions: 9, shotPower: 8, stamina: 8, strength: 5, longShots: 9, attackingPosition: 10, vision: 8, composure: 9 }],
    ['WG_CROSSING', 'Crossing Winger', 'Stays wider and primarily creates through crosses.', { ballControl: 8, dribbling: 8, crossing: 10, shortPassing: 8, longPassing: 6, finishing: 5, volleys: 3, curve: 9, acceleration: 9, sprintSpeed: 9, agility: 8, balance: 7, reactions: 8, shotPower: 5, stamina: 10, strength: 5, longShots: 4, attackingPosition: 7, vision: 8, composure: 8 }],
    ['WG_GOAL_SCORER', 'Goal-Scoring Winger', 'Behaves almost like a wide striker and attacks the box.', { ballControl: 8, dribbling: 9, crossing: 5, shortPassing: 7, longPassing: 3, finishing: 10, volleys: 8, curve: 8, acceleration: 9, sprintSpeed: 9, agility: 9, balance: 8, reactions: 9, shotPower: 9, stamina: 8, strength: 6, longShots: 9, attackingPosition: 10, vision: 6, composure: 10 }],
  ]),
  ST: makeRoles('ST', [
    ['ST_POACHER', 'Poacher', 'Lives around the box and specializes in finishing chances.', { ballControl: 7, dribbling: 6, crossing: 1, shortPassing: 5, longPassing: 1, finishing: 10, headingAccuracy: 8, volleys: 9, curve: 5, acceleration: 8, sprintSpeed: 7, agility: 6, balance: 6, reactions: 10, shotPower: 9, jumping: 8, stamina: 7, strength: 7, longShots: 7, aggression: 6, attackingPosition: 10, vision: 4, composure: 10 }],
    ['ST_MOBILE', 'Mobile Striker', 'Uses pace and movement to run behind the defence.', { ballControl: 8, dribbling: 9, crossing: 2, shortPassing: 6, longPassing: 2, finishing: 10, headingAccuracy: 5, volleys: 8, curve: 6, acceleration: 10, sprintSpeed: 10, agility: 9, balance: 8, reactions: 9, shotPower: 8, jumping: 5, stamina: 9, strength: 6, longShots: 7, aggression: 6, attackingPosition: 10, vision: 5, composure: 9 }],
    ['ST_TARGET', 'Target Man', 'Uses strength, heading and hold-up play to bring others into attack.', { ballControl: 9, dribbling: 5, crossing: 2, shortPassing: 8, longPassing: 4, finishing: 9, headingAccuracy: 10, volleys: 8, curve: 4, acceleration: 4, sprintSpeed: 5, agility: 4, balance: 8, reactions: 9, shotPower: 8, jumping: 10, stamina: 7, strength: 10, longShots: 5, aggression: 9, attackingPosition: 9, vision: 6, composure: 9 }],
    ['ST_COMPLETE', 'Complete Striker', 'Strong across finishing, movement, passing, dribbling and physical play.', { ballControl: 10, dribbling: 9, crossing: 4, shortPassing: 9, longPassing: 5, finishing: 10, headingAccuracy: 8, volleys: 9, curve: 7, acceleration: 8, sprintSpeed: 8, agility: 8, balance: 8, reactions: 10, shotPower: 9, jumping: 8, stamina: 9, strength: 9, longShots: 8, aggression: 7, attackingPosition: 10, vision: 8, composure: 10 }],
    ['ST_FALSE_9', 'False 9', 'Drops deeper to receive the ball and create for teammates.', { ballControl: 10, dribbling: 10, crossing: 5, shortPassing: 10, longPassing: 8, finishing: 8, headingAccuracy: 4, volleys: 6, curve: 8, acceleration: 7, sprintSpeed: 6, agility: 9, balance: 9, reactions: 9, shotPower: 6, jumping: 4, stamina: 8, strength: 6, longShots: 7, aggression: 5, attackingPosition: 8, vision: 10, composure: 10 }],
    ['ST_LONG_SHOT', 'Finesse / Long-Shot Striker', 'Designed specifically for shooting effectively from outside the box.', { ballControl: 9, dribbling: 9, crossing: 3, shortPassing: 7, longPassing: 5, finishing: 10, headingAccuracy: 4, volleys: 9, curve: 10, acceleration: 8, sprintSpeed: 8, agility: 9, balance: 8, reactions: 9, shotPower: 10, jumping: 4, stamina: 8, strength: 6, longShots: 10, aggression: 5, attackingPosition: 9, vision: 7, composure: 10 }],
  ]),
}

export const allRolePresets = Object.values(rolePresets).flat()
